
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-05
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-05
pull_requests: [{"author":{"id":"MDQ6VXNlcjI1MjgzOTIx","is_bot":false,"login":"ishanjainofficial","name":"Ishan Jain"},"headRefName":"ishan-requestTypeDropdown","number":74,"title":"Added dropdown for Request Type","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-05/pull/74"},{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bh-recomm-nevbar","number":73,"title":"added Request tab under Admin","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-05/pull/73"},{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"rz-requestTypeDelete","number":67,"title":"Added DELETE operation for RequestType","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-05/pull/67"}]
