
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-rec-f24-05
owner: ucsb-cs156-f24
repo_name: proj-rec-f24-05
pull_requests: [{"author":{"id":"U_kgDOB1P9DQ","is_bot":false,"login":"bgggggh","name":""},"headRefName":"bh-request-utils","number":55,"title":"added utils and tests for requestType","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-05/pull/55"},{"author":{"id":"MDQ6VXNlcjczOTIyMDEz","is_bot":false,"login":"basperheim1","name":""},"headRefName":"ba-post-request","number":53,"title":"BA Post Request ","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-05/pull/53"},{"author":{"id":"U_kgDOB1QJQw","is_bot":false,"login":"RyanZanone","name":""},"headRefName":"rz-backendRequestTypeTable","number":48,"title":"Add Entity, Repository and DB Migration files for RequestType","url":"https://github.com/ucsb-cs156-f24/proj-rec-f24-05/pull/48"}]
